### ISSUE TITLE
Draft is not an `Draft<T>`

### ISSUE THREAD

**Issue by chpio** [unadlib/use-mutative#2]
Hi,
the passed-in draft has the type `T` (but i would expect it to be `Draft<T>`), making the draft readonly if the original data type was defined as readonly.

**Comment by unadlib** [comment]
> Hi, the passed-in draft has the type `T` (but i would expect it to be `Draft<T>`), making the draft readonly if the original data type was defined as readonly.

Could you provide an example? In fact, you can use `draft: Draft<typeof initState>`.

**Comment by chpio** [comment]
For example the same way you would in immer. By defining the fields in your state as immutable with `readonly`, but get mutable fields in the produce fn: https://immerjs.github.io/immer/typescript

**Comment by unadlib** [comment]
hi @chpio , we have released version 1.0 and comprehensively fixed all known issues. Feel free to give use-mutative a try!
